### ISSUE TITLE
wiring diagram missing?

### ISSUE THREAD

**Issue by hamiltonia** [graham-jessup/Watchman#1]
I don't see any reference to wiring diagram, can you please share how you're connecting the two raspberry pi, and laser LED including mosfet?

**Comment by hamiltonia** [comment]
From what I can see these are the pins, does that look right? 

[Arduino UNO: 0(RX), 1(TX)](https://www.arduino.cc/reference/en/language/functions/communication/serial/)
[Raspberry Pi Zero: 10 (RX), 8 (TX)](https://pinout.xyz/pinout/serial_pi_zero)

Also did you just solder directly to the vision bonnet, or some other magic?

**Comment by graham-jessup** [comment]
I don't have the exact wiring details with me at the moment, but here's some info to start:

The AIY Vision Bonnet is a "Hat" on the Raspberry Pi Zero, it's connected via to the Pi headers and a ribbon cable. The vision bonnet and the Pi Zero both come from the AIY vision kit, so the AIY [instructions](https://aiyprojects.withgoogle.com/vision#assembly-guide) covers the wiring/assembly of the AIY Hat, Arcade Button, and Camera.

The Pi Zero communicates with the Arduino via USB serial, there's a micro-usb to USB-B cable that connects the Pi Zero to the Arduino Uno.

The Arduino Uno has an Adafruit 16 channel servo shield attached. The servos attach to the servo shield. 

The laser mosfet is controlled by digital pin 2 of the Arduino, which is accessed via the headers on the servo shield. I can't remember the exact details of the mosfet power, so I'll have to get back to you on that.

Ultimately, I'd like to make a Fritzing-style wiring diagram for this project. That will require me to download and learn Fritzing, so that will take some time. 

In the meantime, I'm happy to keep answering questions, and I'll see if I can provide more relevant photos of the wiring.

**Comment by hamiltonia** [comment]
Great - thanks! I didn't even think that was a thing. I found some articles on Raspberry Pi to Arduino via USB, I'll see if I can figure it out.

**Comment by graham-jessup** [comment]
Hope you've had some success! I just added two basic wiring diagrams that should help with the basic layout.

**Comment by hamiltonia** [comment]
Thanks much for the diagrams, I'm still plugging away in my spare time. Up and running but badly out of focus :D
